spring:
  jackson:
    default-property-inclusion: non_null
    deserialization:
      READ_ENUMS_USING_TO_STRING: true
      FAIL_ON_UNKNOWN_PROPERTIES: true
  datasource:
    url: jdbc:h2:mem:film
    username: msa
    password: msa
    driverClassName: org.h2.Driver
  liquibase:
    change-log: classpath:db/db.changelog-master.yaml
    enabled: true
  jpa:
    properties:
      hibernate:
        dialect:org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate