CREATE TABLE film
(
    id           INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(200)  NOT NULL,
    description  VARCHAR(1000) NOT NULL,
    type         VARCHAR(25)   NOT NULL,
    genre        VARCHAR(20)   NOT NULL,
    release_date DATE          NOT NULL
);